# Generated by Django 3.2.19 on 2024-10-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_hyperreactive_new_means'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligandable',
            name='cell_line_datasets',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='datasetid',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='hyperreactive',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='hyperreactive_datasets',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='identified',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='identified_datasets',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='level',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='ligandable_datasets',
        ),
        migrations.RemoveField(
            model_name='ligandable',
            name='redox_datasets',
        ),
        migrations.AddField(
            model_name='ligandable',
            name='acrylamide',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ligandable',
            name='bromoacetamide',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ligandable',
            name='chloroacetamide',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ligandable',
            name='compounds',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ligandable',
            name='datasets',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ligandable',
            name='dimethylfumarate',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ligandable',
            name='other',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ligandable',
            name='ligandable',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Identified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('proteinid', models.CharField(max_length=20)),
                ('cysteineid', models.CharField(max_length=20)),
                ('resid', models.CharField(max_length=20)),
                ('datasetid', models.CharField(max_length=20)),
                ('identified', models.CharField(max_length=3)),
                ('identified_datasets', models.CharField(max_length=20)),
                ('ligandable_datasets', models.CharField(max_length=20)),
                ('ligandable', models.CharField(max_length=3)),
                ('cell_line_datasets', models.CharField(max_length=20)),
                ('hyperreactive', models.CharField(max_length=20, null=True)),
                ('hyperreactive_datasets', models.CharField(max_length=20, null=True)),
                ('redox_datasets', models.CharField(max_length=20, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.uploadfile')),
            ],
        ),
    ]
