# Generated by Django 3.2.19 on 2025-02-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20241015_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinid', models.CharField(max_length=20)),
                ('cysteineid', models.CharField(max_length=20)),
                ('resid', models.CharField(max_length=20)),
                ('desai_percentage', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.uploadfile')),
            ],
        ),
    ]
