# Generated by Django 3.2.19 on 2025-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_redox'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperreactive',
            name='test_mean',
            field=models.FloatField(null=True),
        ),
    ]
